### ISSUE TITLE
Panic if downloads fails because no more disk space.

### ISSUE THREAD

**Issue by zaibon** [g8os/g8ufs#2]
![2017-02-24_1108x817_scrot](https://cloud.githubusercontent.com/assets/303164/23302521/47cacb46-fa8f-11e6-82c9-71a0a22c31b7.png)

flist used : [flist-f01d588b631d7e6d890e96711bf28e61.db.tar.gz](https://github.com/g8os/g8ufs/files/799173/flist-f01d588b631d7e6d890e96711bf28e61.db.tar.gz)

Reproduce:
```
cl.container.create('http://172.20.0.1:8000/flist-f01d588b631d7e6d890e96711bf28e61.db.tar.gz')
c2 = cl.container.client(2)  
c2.bash('/opt/bin/ardb-server')
```
I think the crash happened because I didn't had disk space anymore.
I think we should return an IO error but not allow to completly crash the filesystem

**Comment by muhamadazmy** [comment]
This can never happen again since we don't run g8ufs inside core0 anymore, it starts now as own process. Even then, the process will never crash if it ran out of cache space, instead an error is returned.
